"""create_task_overlay

Revision ID: 7173ec284d38
Revises: 
Create Date: 2026-06-09 11:09:06.631289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7173ec284d38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_overlay',
    sa.Column('tasklist_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('rank', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tasklist_id', 'task_id')
    )
    with op.batch_alter_table('task_overlay', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_overlay_rank'), ['rank'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_overlay', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_overlay_rank'))

    op.drop_table('task_overlay')
    # ### end Alembic commands ###
